bot_to_run: Console

static_bot_options:
  help_msg: "This is a simple echo-bot, it sends back your messages, to choose number of message repeats send /repeat command"
  repeat_msg: "Please, choose number of times to repeat your messages: "
  default_repeat_number: 1

telegram_bot_token: "000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
